### ISSUE TITLE
There aren't any files in the 'util' folder.

### ISSUE THREAD

**Issue by nilaeus** [aeioio/mbt#1]
The files should be changed so that there is no include to the files, and no functions randomly called.

**Comment by mariobrostech** [comment]
You're speaking in Pirate Speak. Can you be more specific?

**Comment by nilaeus** [comment]
@mariobrostech 
I deleted the `/home7/aerakorc/public_html/util/` folder.
That won't be used anymore.
Color Atop can be used instead (Coming soon)
