### ISSUE TITLE
HTML vs. PHP - Discrepancies

### ISSUE THREAD

**Issue by TheRoyalBlock** [aeioio/mbt#7]
Php? WHY?! If you declare the doctype as html, then what's the point of making the file extension php?

**Comment by mariobrostech** [comment]
For headers and footers being synced across all pages on the site. Most of the other elements of the pages are still all HTML, CSS, and JS.
If you believe something I say is incorrect, please point it out. I'm always learning!

**Comment by TheRoyalBlock** [comment]
Well, that was a really late response... Either way, it's a lot more practical to just have HTML instead of php. Manually coding it allows you to set active tabs etc

**Comment by mariobrostech** [comment]
Yeah, but syncing all titles from header and footer files is much easier with PHP. Also, PHP allows for more expansion in the future. Our switch to Nodejs will also help support locally hosting these PHP sites as well.

**Comment by nilaeus** [comment]
My goal is to help you use 0% PHP and 100% Node.js and other modern tools.

**Comment by TheRoyalBlock** [comment]
^ Good idea, @nilaeus
